import { Course, QuizQuestion } from '@/lib/types'

export const courses: Course[] = [
  {
    id: 'eng-201',
    code: 'ENG-201',
    title: 'Introduction to Fictional and Non-fictional Narrative',
    semester: 'BS English — Semester III',
    description:
      'A comprehensive study of both fictional and non-fictional narratives, focusing on point of view, tone, theme, and the key forms of prose writing from the novel to the memoir.',
    objectives: [
      'Understand the distinctions between fictional and non-fictional narratives',
      'Analyze key elements: POV, theme, style, and tone',
      'Study major novel genres and their characteristics',
      'Engage in close reading of selected fictional and non-fictional texts',
    ],
    topics: [
      {
        title: 'Section I: Theory',
        subtopics: [
          'Definitions and distinctions between fictional and non-fictional narratives',
          'Key Forms of Fictional Prose: Novel, Short Story, Novella',
          'Key Concepts: Plot Structure, Characters & Characterization, Setting',
          'Point of View (POV), Theme, Style and Tone',
        ],
      },
      {
        title: 'The Novel and Its Genres',
        subtopics: [
          'The Epistolary Novel',
          'The Picaresque Novel',
          'Coming-of-age Novel / Bildungsroman',
          'The Historical Novel',
          'The Novel of Manners',
          'The Gothic Novel',
          'The Realistic Novel',
          'Modern Novel',
          'The Postmodern Novel',
          'The Graphic Novel',
          'Other forms: Detective, Mystery, Thriller, Fantasy, Dystopian Fiction, Science Fiction',
        ],
      },
      {
        title: 'Key Forms of Non-fictional Narrative',
        subtopics: [
          'Essay: personal, critical, Nature & Essay in theory',
          'Biography & Autobiography',
          'Travelogues',
          'Memoir',
          'Creative Non-fiction',
        ],
      },
      {
        title: 'Section II: Theory into Action — Set Texts',
        subtopics: [
          'Novel: Lord of the Flies by William Golding',
          'Novel: Moth Smoke by Mohsin Hamid',
          'Short Story: Story of an Hour by Kate Chopin',
          'Short Story: The Fall of the House of Usher by Edgar Allan Poe',
          'Short Story: The Necklace by Guy de Maupassant',
          'Short Story: Cat in the Rain by Ernest Hemingway',
          'Short Story: Araby by James Joyce',
          'Essay: Of Marriage and Single Life by Francis Bacon',
          'Essay: A Free Man\'s Worship by Bertrand Russell',
          'Essay: Shooting an Elephant by George Orwell',
          'Essay: On Liberty (Chapter 1) by John Stuart Mill',
          'Essay: Illness as Metaphor by Susan Sontag (Chapter 9)',
        ],
      },
    ],
    color: '#7C3AED',
  },
  {
    id: 'eng-203',
    code: 'ENG-203',
    title: 'World Literature',
    semester: 'BS English — Semester III',
    description:
      'A comprehensive exploration of World Literature spanning various periods, regions, and genres — from ancient epics to contemporary postcolonial writing.',
    objectives: [
      'Introduce students to literary works from diverse cultures and historical periods',
      'Develop critical reading and analytical skills through world literature',
      'Explore how literature reflects cultural, social, and political contexts',
      'Encourage comparative thinking and cross-cultural understanding',
    ],
    topics: [
      {
        title: 'Introduction to World Literature',
        subtopics: [
          'Defining World Literature',
          'Historical Development of the concept',
          'Transnational, Comparative, and Postcolonial literatures',
          'The role of translation in World Literature',
          'Reading: Excerpts from What is World Literature? by David Damrosch',
        ],
      },
      {
        title: 'An Introduction to Ancient Epics and Mythologies',
        subtopics: [
          'The Epic of Gilgamesh (Mesopotamia)',
          'The Mahabharata (India)',
          'The Odyssey by Homer (Greece)',
          'The Analects by Confucius (China)',
          'The Divine Comedy by Dante (Italy)',
          'The Tale of Genji by Murasaki Shikibu (Japan)',
          'Beowulf (Anglo-Saxon)',
          'Themes: heroism, fate, and the divine/religion',
        ],
      },
      {
        title: 'Reading Africa & the Caribbean',
        subtopics: [
          'Fiction: Things Fall Apart by Chinua Achebe (Nigeria)',
          'Poems: A Far Cry from Africa by Derek Walcott (St Lucia)',
          'Poem: Home by Warsan Shire (Somalia/UK)',
          'Themes: Colonialism, cultural clash, tradition vs. change, refugee crisis, displacement, belonging',
        ],
      },
      {
        title: 'Reading the Arab World',
        subtopics: [
          'Fiction: Zaabalawi by Naguib Mahfouz (Egypt)',
          'Poem: To My Mother by Mahmoud Darwish (Palestine)',
          'Themes: Love, exile, spirituality, homeland',
        ],
      },
      {
        title: 'Reading Latin America',
        subtopics: [
          'Fiction: The Handsomest Drowned Man in the World by Gabriel García Márquez (Colombia)',
          'Poem: Walking Around by Pablo Neruda (Chile)',
          'Themes: Fate, magical realism, alienation, existentialism, disillusionment with modern life',
        ],
      },
      {
        title: 'Reading Asia',
        subtopics: [
          'Fiction: Toba Tek Singh by Manto (Pakistan)',
          'Fiction: Exit West by Mohsin Hamid (Pakistan/Britain)',
          'Fiction: The Nose by Ryūnosuke Akutagawa (Japan)',
          'Fiction: The Bet by Anton Chekhov (Russia)',
          'Poems: We Sinful Women by Kishwar Naheed (Pakistan)',
          'Poem: An Introduction by Kamala Das (India)',
          'Themes: Partition, Migration, feminism, identity crisis, societal pressure',
        ],
      },
      {
        title: 'Reading Europe & the USA',
        subtopics: [
          'Fiction: Metamorphosis by Franz Kafka (Austria-Hungary/Czechoslovakia)',
          'Poem: Still I Rise by Maya Angelou (African-American)',
          'Poem: Raven by Edgar Allan Poe',
          'Themes: Alienation, transformation, modernity, resistance, feminism, loss',
        ],
      },
      {
        title: 'Reading Indigenous Voices',
        subtopics: [
          'Poem: Remember by Joy Harjo (United States)',
          'Themes: Native American identity, memory, cultural inheritance',
        ],
      },
    ],
    color: '#0891B2',
  },
  {
    id: 'eng-205',
    code: 'ENG-205',
    title: 'Semiotics',
    semester: 'BS English — Semester III',
    description:
      'An introduction to semiotics from Saussure to contemporary socio-semiotics, covering the study of signs, symbols, and meaning-making in communication.',
    objectives: [
      'Introduce students to the basics of semiotics and sign theory',
      'Understand the development from Saussure to contemporary semiotics',
      'Apply semiotic analysis to texts and communication',
      'Develop critical thinking through semiotic frameworks',
    ],
    topics: [
      {
        title: 'Introduction to Semiotics',
        subtopics: [
          'What is Semiotics? Definition and Introduction',
          'Historical Perspective',
          'Relation to Linguistics',
          'Key terms in Semiotics',
        ],
      },
      {
        title: 'Key Terms and Concepts',
        subtopics: [
          'Signs: signification, signifier and signified',
          'Symbolic Signs, Iconic Signs, Indexical Signs',
          'Icons',
          'Indices',
          'Symbols',
          'Paradigmatic relations',
          'Syntagmatic relations',
          'Denotation',
          'Connotation',
        ],
      },
      {
        title: 'Key Thinkers in Semiotics',
        subtopics: [
          'Ferdinand de Saussure (1857–1913) — founder of modern linguistics and semiology',
          'Charles Sanders Peirce (1839–1914) — triadic model of the sign',
          'Roman Jakobson (1896–1982) — communication functions',
          'Charles William Morris (1901–1979) — behavioural semiotics',
          'Roland Barthes (1915–1980) — mythology and cultural semiotics',
        ],
      },
      {
        title: 'Three Types of Semiotics',
        subtopics: [
          'Cognitive Semiotics — meaning in the mind',
          'Social and Cultural Semiotics — meaning in society',
          'Visual Semiotics — meaning in images',
        ],
      },
    ],
    recommendedReadings: [
      'Chandler, Daniel. (2002). Semiotics: The Basics. 2nd ed. New York: Routledge.',
      'Martin, Bronwen and Ringham, Felizitas. (2006). Key Terms in Semiotics. Continuum: New York.',
      'Danesi, Marcel. (2007). The Quest for Meaning: A Guide to Semiotic Theory and Practice.',
      'Eco, Umberto (1977): A Theory of Semiotics. London: Macmillan.',
    ],
    color: '#059669',
  },
  {
    id: 'hrs-201',
    code: 'HRS-201',
    title: 'Human Rights',
    semester: 'BS English — Semester III',
    description:
      'A course dealing with good citizenship values, human rights components, religious tolerance, cross-cultural understanding, and the recognition of human dignity and diversity.',
    objectives: [
      'Promote human values including religious tolerance and HR awareness',
      'Develop cross-cultural understanding and recognition of diversity',
      'Relate human progress through good citizenship and social harmony',
      'Understand the evolution and key principles of human rights',
    ],
    topics: [
      {
        title: 'Foundational Documents',
        subtopics: [
          'The Last Address of the Holy Prophet (Peace be upon Him)',
          'The United Nations Human Rights Charter',
        ],
      },
      {
        title: 'Core Concepts in Human Rights',
        subtopics: [
          'What is Human Rights (HR)?',
          'Evolution of the Concept of HR',
          'Four Fundamentals in HR: freedom, equality, justice, and human dignity',
          'Universal Declaration of HR',
          'Three Key Principles: inalienability, indivisibility, and universality',
          'Are HR Universal? (debate/discussion)',
        ],
      },
      {
        title: 'Human Rights in Context',
        subtopics: [
          'HR in South Asia: Issues and Challenges',
          'Rights of Women',
          'Rights of Children (debate/discussion on child labour, etc.)',
        ],
      },
    ],
    recommendedReadings: [
      'Dean, B. Joldoshalieva, R. & Sayani, F. (2006). Creating a Better World. Karachi: Aga Khan University.',
      'Ed. Williams, Isabel. (2008). Teaching Human Rights through English Education. Karachi: Oxford University Press.',
    ],
    color: '#DC2626',
  },
  {
    id: 'inct-201',
    code: 'INCT-201',
    title: 'Applications of Information & Communication Technologies',
    semester: 'BS English — Semester III',
    description:
      'An introductory course in Computer Science for beginners covering computing history, hardware, software, networking, and internet technologies.',
    objectives: [
      'Understand basics of computing technology (CLO-1)',
      'Perform number system conversions and arithmetic (CLO-2)',
      'Gain knowledge of types of software (CLO-3)',
      'Understand computing-related technologies (CLO-4)',
    ],
    topics: [
      {
        title: 'History and Basics of Computing',
        subtopics: [
          'Brief history of Computer',
          'Four Stages of History',
          'Computer Elements: Processor, Memory, Hardware, Software',
          'Application Software: its uses and limitations',
          'System Software: its importance and types',
          'Types of Computer: Super, Mainframe, Mini and Micro Computer',
          'Introduction to CBIS (Computer Based Information System)',
        ],
      },
      {
        title: 'Input, Output and Storage',
        subtopics: [
          'Methods of Input and Processing',
          'Organizing Computer Facility: Centralized, Distributed, Decentralized',
          'Input Devices: Keyboard types, Terminal types, SDA, Pointing Devices',
          'Output Devices: Soft/Hard Copies, Monitors, Printers, Plotters',
          'Computer Viruses and its Forms',
          'Storage Units: Primary and Secondary Memories',
          'RAM and its Types, Cache, Hard Disks',
          'Working of Hard Disk, Diskettes, RAID, Optical Disk Storages (DVD, CD ROM)',
          'Magnetic Types, Backup System',
        ],
      },
      {
        title: 'Data Communications and Networking',
        subtopics: [
          'Data Communications, Data Communication Model',
          'Data Transmission: Digital and Analog',
          'Modems, Asynchronous and Synchronous Transmission',
          'Simplex, Half Duplex, Full Duplex Transmission',
          'Communications Media: Cables and Wireless',
          'Protocols and Network Topologies: Star, Bus, Ring',
          'LAN and Internet',
          'A Brief History of ARPA Net',
          'Web Link, Browser, Internet Services Providers',
          'Function and Features of Browser, Search Engines',
          'Common Services available on Internet',
        ],
      },
    ],
    recommendedReadings: [
      'Parker, Charles S. Understanding Computers: Today and Tomorrow. Course Technology, Boston.',
      'Livesley, Robert Kenneth. An introduction to automatic digital computers. Cambridge University Press, 2017.',
      'Sinha, Pradeep K., and Priti Sinha. Computer fundamentals. BPB publications, 2010.',
      'Goel, Anita. Computer fundamentals. Pearson Education India, 2010.',
    ],
    color: '#D97706',
  },
  {
    id: 'esci-201',
    code: 'ESCI-201',
    title: 'Environmental Science',
    semester: 'BS English — Semester III',
    description:
      'An orientation on the evolution and scope of Environmental Science, motivating students to think beyond basic sciences toward decision sciences and sustainable development.',
    objectives: [
      'Learn the importance of Environmental Science in human life',
      'Understand its relationship with various segments of society and development',
      'Become familiar with current national, regional and global environmental challenges',
      'Understand the principles of sustainable development',
    ],
    topics: [
      {
        title: 'Environment: The Four Spheres',
        subtopics: [
          'The Atmosphere: Layered Structure and Composition',
          'Hydrosphere: Water Cycle, Major Water Compartments',
          'Biosphere: Major Biomes',
          'Lithosphere: Minerals and Rocks, Rock Types, Plate Tectonics',
        ],
      },
      {
        title: 'Atmospheric Pollution',
        subtopics: [
          'Types, Sources, Causes and effects of major air pollutants',
          'COx, Particulate Matter, NOx, SOx, Tropospheric Ozone',
          'Volatile Organic Compounds, Dioxins',
          'Regional and Global air pollution: Acid Rain, Ozone Depletion',
          'Greenhouse Effect and Global Warming',
          'Montreal Protocol and Kyoto Protocol',
        ],
      },
      {
        title: 'Water Pollution',
        subtopics: [
          'Types, sources, causes and effects of major water pollutants',
          'Synthetic Organic Chemicals, Oxygen Demanding Wastes',
          'Plant Nutrients, Thermal Pollution, Infectious Agents',
          'Sediments, Radioactivity, Heavy Metals and Acids',
          'Drinking water quality and standards',
        ],
      },
      {
        title: 'Land Pollution & Environmental Management',
        subtopics: [
          'Solid Waste Management and Disposal',
          'Role of Remote Sensing and GIS in Environmental Science',
          'Population Planning',
          'Environmental aspects: physic-chemical, biological, socio-economic',
          'Environmental problems: local, regional and global level',
          'Environmental Challenges: Sustainability',
          'Convergence of ecology with economic and sociology',
        ],
      },
    ],
    color: '#16A34A',
  },
]

// Built-in quiz questions for each course (fallback if Firestore has none)
export const builtInQuizzes: Record<string, QuizQuestion[]> = {
  'eng-201': [
    {
      id: 'q1',
      question: 'Which of the following best defines a "novella"?',
      options: [
        'A long fictional work with complex characters and multiple plotlines',
        'A short fictional prose work, longer than a short story but shorter than a novel',
        'A non-fictional account of real events',
        'A dramatic work intended for stage performance',
      ],
      correct: 1,
      explanation: 'A novella is an intermediate prose form — longer than a short story but shorter and less complex than a full novel.',
    },
    {
      id: 'q2',
      question: 'Point of View (POV) in a narrative refers to:',
      options: [
        'The moral lesson of the story',
        'The time period in which the story is set',
        'The perspective from which the story is told',
        'The climax of the plot',
      ],
      correct: 2,
      explanation: 'POV determines who narrates the story — first person, second person, or third person (limited or omniscient).',
    },
    {
      id: 'q3',
      question: '"Lord of the Flies" was written by:',
      options: ['Mohsin Hamid', 'William Golding', 'James Joyce', 'George Orwell'],
      correct: 1,
      explanation: 'William Golding wrote Lord of the Flies (1954), a novel about boys stranded on an uninhabited island.',
    },
    {
      id: 'q4',
      question: 'Which type of novel focuses on the moral and psychological growth of the protagonist from youth to adulthood?',
      options: ['Gothic Novel', 'Epistolary Novel', 'Bildungsroman', 'Picaresque Novel'],
      correct: 2,
      explanation: 'Bildungsroman (coming-of-age novel) traces the protagonist\'s development from childhood to maturity.',
    },
    {
      id: 'q5',
      question: '"Shooting an Elephant" is an essay written by:',
      options: ['Francis Bacon', 'Bertrand Russell', 'George Orwell', 'John Stuart Mill'],
      correct: 2,
      explanation: 'George Orwell wrote "Shooting an Elephant" (1936), a reflective essay on imperialism based on his experience in Burma.',
    },
    {
      id: 'q6',
      question: 'An Epistolary Novel is written in the form of:',
      options: ['Diary entries only', 'Letters, diary entries, or documents', 'Newspaper articles', 'Oral storytelling'],
      correct: 1,
      explanation: 'Epistolary novels are told through letters, diary entries, or other documents written by characters.',
    },
    {
      id: 'q7',
      question: '"Story of an Hour" was written by:',
      options: ['Ernest Hemingway', 'Kate Chopin', 'Edgar Allan Poe', 'Guy de Maupassant'],
      correct: 1,
      explanation: 'Kate Chopin wrote "The Story of an Hour" (1894), exploring themes of freedom and marriage.',
    },
    {
      id: 'q8',
      question: 'Which of the following is a form of Non-fictional Narrative?',
      options: ['Gothic Novel', 'Science Fiction', 'Travelogue', 'Postmodern Novel'],
      correct: 2,
      explanation: 'Travelogues are non-fictional accounts of journeys and places visited by the author.',
    },
    {
      id: 'q9',
      question: '"Moth Smoke" was written by:',
      options: ['Chinua Achebe', 'Mohsin Hamid', 'Franz Kafka', 'Gabriel García Márquez'],
      correct: 1,
      explanation: 'Mohsin Hamid wrote Moth Smoke (2000), a Pakistani novel exploring themes of class, drugs, and moral decline.',
    },
    {
      id: 'q10',
      question: 'Which element of fiction refers to the time and place where a story unfolds?',
      options: ['Theme', 'Tone', 'Setting', 'Point of View'],
      correct: 2,
      explanation: 'Setting refers to the time, place, and environment in which the narrative takes place.',
    },
  ],
  'eng-203': [
    {
      id: 'q1',
      question: '"Things Fall Apart" was written by:',
      options: ['Naguib Mahfouz', 'Chinua Achebe', 'Gabriel García Márquez', 'Franz Kafka'],
      correct: 1,
      explanation: 'Chinua Achebe (Nigeria) wrote Things Fall Apart (1958), a foundational work in African literature.',
    },
    {
      id: 'q2',
      question: 'The concept of "World Literature" was significantly theorized by:',
      options: ['Roland Barthes', 'David Damrosch', 'Ferdinand de Saussure', 'Umberto Eco'],
      correct: 1,
      explanation: 'David Damrosch\'s What is World Literature? (2003) is a key text in defining and theorizing World Literature.',
    },
    {
      id: 'q3',
      question: '"Metamorphosis" was written by:',
      options: ['Pablo Neruda', 'Franz Kafka', 'Anton Chekhov', 'Dante Alighieri'],
      correct: 1,
      explanation: 'Franz Kafka (Austria-Hungary/Czechoslovakia) wrote The Metamorphosis (1915).',
    },
    {
      id: 'q4',
      question: 'Which poem is associated with themes of exile and homeland in Palestinian literature?',
      options: [
        'Still I Rise by Maya Angelou',
        'Remember by Joy Harjo',
        'To My Mother by Mahmoud Darwish',
        'Walking Around by Pablo Neruda',
      ],
      correct: 2,
      explanation: 'Mahmoud Darwish\'s "To My Mother" is a celebrated Palestinian poem about love, homeland, and exile.',
    },
    {
      id: 'q5',
      question: 'Magical realism is most associated with the literature of:',
      options: ['Europe', 'Latin America', 'South Asia', 'Africa'],
      correct: 1,
      explanation: 'Magical realism is a hallmark of Latin American literature, most notably in the works of Gabriel García Márquez.',
    },
    {
      id: 'q6',
      question: '"Toba Tek Singh" by Saadat Hasan Manto deals with:',
      options: ['The Arab-Israeli conflict', 'The Partition of India and Pakistan', 'Japanese imperialism', 'Latin American revolution'],
      correct: 1,
      explanation: 'Manto\'s "Toba Tek Singh" is a powerful story about the partition of India and Pakistan in 1947.',
    },
    {
      id: 'q7',
      question: '"Still I Rise" was written by:',
      options: ['Joy Harjo', 'Warsan Shire', 'Maya Angelou', 'Kishwar Naheed'],
      correct: 2,
      explanation: 'Maya Angelou wrote "Still I Rise," a poem about resilience and resistance against oppression.',
    },
    {
      id: 'q8',
      question: 'The Epic of Gilgamesh originates from:',
      options: ['Ancient Greece', 'Ancient India', 'Mesopotamia', 'Ancient China'],
      correct: 2,
      explanation: 'The Epic of Gilgamesh is an ancient Mesopotamian poem and one of the earliest great works of literature.',
    },
    {
      id: 'q9',
      question: '"Exit West" by Mohsin Hamid primarily deals with:',
      options: ['Environmental destruction', 'Migration and displacement', 'Colonialism in Africa', 'The Cold War'],
      correct: 1,
      explanation: 'Exit West (2017) uses magical doors as a metaphor to explore migration, displacement, and refugee experience.',
    },
    {
      id: 'q10',
      question: 'The role of translation in World Literature is significant because:',
      options: [
        'It removes cultural nuance from texts',
        'It allows texts to travel across linguistic and cultural boundaries',
        'It is only relevant for ancient texts',
        'It replaces the need to study original languages',
      ],
      correct: 1,
      explanation: 'Translation enables literary works to circulate globally, making World Literature possible across languages.',
    },
  ],
  'eng-205': [
    {
      id: 'q1',
      question: 'Semiotics is the study of:',
      options: ['Grammar and syntax', 'Signs and meaning-making', 'Poetic metre', 'Narrative structure'],
      correct: 1,
      explanation: 'Semiotics is the study of signs and symbols and how they create meaning in communication.',
    },
    {
      id: 'q2',
      question: 'Who is considered the founder of modern semiology/linguistics?',
      options: ['Roland Barthes', 'Charles Sanders Peirce', 'Ferdinand de Saussure', 'Roman Jakobson'],
      correct: 2,
      explanation: 'Ferdinand de Saussure (1857–1913) is the father of modern linguistics and semiology.',
    },
    {
      id: 'q3',
      question: 'In Saussure\'s model, the "signifier" refers to:',
      options: [
        'The concept or mental image',
        'The sound-image or written form',
        'The real-world object being referenced',
        'The cultural context of meaning',
      ],
      correct: 1,
      explanation: 'The signifier is the sound-image or written/spoken form, while the signified is the concept/meaning.',
    },
    {
      id: 'q4',
      question: 'An "iconic sign" is one that:',
      options: [
        'Is arbitrary and has no resemblance to what it represents',
        'Resembles or looks like the object it represents',
        'Is caused by or directly connected to its object',
        'Is purely conventional',
      ],
      correct: 1,
      explanation: 'An iconic sign resembles the object it represents — like a portrait or a map.',
    },
    {
      id: 'q5',
      question: 'Paradigmatic relations in semiotics refer to:',
      options: [
        'The sequence of signs in a message',
        'The set of signs that can substitute each other in a given context',
        'The visual arrangement of signs',
        'The historical development of a sign system',
      ],
      correct: 1,
      explanation: 'Paradigmatic relations involve choices — which sign to select from a set of possible alternatives (e.g., choosing a word from synonyms).',
    },
    {
      id: 'q6',
      question: 'Roland Barthes is known for applying semiotics to:',
      options: [
        'Mathematical logic',
        'Computer programming',
        'Mythology and popular culture',
        'Legal discourse',
      ],
      correct: 2,
      explanation: 'Roland Barthes applied semiotic analysis to everyday cultural phenomena and myths in works like Mythologies (1957).',
    },
    {
      id: 'q7',
      question: '"Denotation" in semiotics means:',
      options: [
        'The implied or cultural meaning of a sign',
        'The literal or primary meaning of a sign',
        'The emotional response to a sign',
        'The historical origin of a sign',
      ],
      correct: 1,
      explanation: 'Denotation is the direct, literal meaning of a sign, as opposed to connotation which is the secondary/cultural meaning.',
    },
    {
      id: 'q8',
      question: 'Charles Sanders Peirce proposed a _______ model of the sign.',
      options: ['Binary', 'Quadratic', 'Triadic', 'Linear'],
      correct: 2,
      explanation: 'Peirce\'s triadic model consists of the Representamen, the Object, and the Interpretant.',
    },
    {
      id: 'q9',
      question: 'Visual Semiotics is concerned with:',
      options: [
        'Meaning in spoken language only',
        'Meaning created through images, colors, and visual composition',
        'Meaning in written texts only',
        'The neuroscience of perception',
      ],
      correct: 1,
      explanation: 'Visual Semiotics studies how images, colors, and visual elements create and communicate meaning.',
    },
    {
      id: 'q10',
      question: 'Syntagmatic relations refer to:',
      options: [
        'The possible substitutions for a sign',
        'The sequential combination of signs in a structure',
        'The cultural codes behind signs',
        'The emotional connotations of signs',
      ],
      correct: 1,
      explanation: 'Syntagmatic relations describe how signs are combined sequentially — like words in a sentence.',
    },
  ],
  'hrs-201': [
    {
      id: 'q1',
      question: 'The Universal Declaration of Human Rights was adopted by the United Nations in:',
      options: ['1945', '1948', '1950', '1966'],
      correct: 1,
      explanation: 'The UDHR was adopted by the UN General Assembly on December 10, 1948.',
    },
    {
      id: 'q2',
      question: 'Which are the Four Fundamentals of Human Rights?',
      options: [
        'Life, liberty, property, and education',
        'Freedom, equality, justice, and human dignity',
        'Peace, security, welfare, and progress',
        'Citizenship, nationality, identity, and culture',
      ],
      correct: 1,
      explanation: 'The four fundamentals of Human Rights are freedom, equality, justice, and human dignity.',
    },
    {
      id: 'q3',
      question: 'The principle of "inalienability" in Human Rights means:',
      options: [
        'Rights can be taken away by the government',
        'Rights are only for citizens of a country',
        'Rights cannot be taken away or given up',
        'Rights are dependent on social status',
      ],
      correct: 2,
      explanation: 'Inalienability means human rights cannot be taken away or surrendered — they belong to every person inherently.',
    },
    {
      id: 'q4',
      question: 'The principle of "universality" in Human Rights means:',
      options: [
        'Rights apply only in developed countries',
        'Rights apply equally to all human beings everywhere',
        'Rights are culturally relative',
        'Rights are granted by governments',
      ],
      correct: 1,
      explanation: 'Universality means that human rights apply equally to every person regardless of nationality, culture, or religion.',
    },
    {
      id: 'q5',
      question: 'Which document is studied in HRS-201 regarding the Last Address of the Holy Prophet (PBUH)?',
      options: [
        'The Treaty of Hudaybiyyah',
        'The Sermon at the Farewell Pilgrimage (Khutbat-ul-Wida)',
        'The Medina Charter',
        'The Treaty of Madinah',
      ],
      correct: 1,
      explanation: 'The Last Address/Farewell Sermon of the Prophet (PBUH) at Hajjat-ul-Wida contains key principles of human rights including equality and dignity.',
    },
    {
      id: 'q6',
      question: 'Child labour is discussed in HRS-201 under the topic of:',
      options: ['HR in South Asia', 'Rights of Women', 'Rights of Children', 'Four Fundamentals of HR'],
      correct: 2,
      explanation: 'Rights of Children, including debates around child labour, is a specific topic in the HRS-201 course.',
    },
    {
      id: 'q7',
      question: 'The principle of "indivisibility" of Human Rights means:',
      options: [
        'Civil rights are more important than economic rights',
        'All human rights are equally important and interconnected',
        'Rights can be divided into categories by the state',
        'Only political rights are truly universal',
      ],
      correct: 1,
      explanation: 'Indivisibility means all human rights — civil, political, economic, social, cultural — are equally important and cannot be separated.',
    },
    {
      id: 'q8',
      question: 'Which of the following is a major human rights issue in South Asia discussed in HRS-201?',
      options: [
        'Space exploration rights',
        'Minority rights, gender inequality, and religious intolerance',
        'Digital privacy exclusively',
        'Post-colonial land redistribution only',
      ],
      correct: 1,
      explanation: 'South Asian HR issues include minority rights, gender inequality, religious intolerance, child rights, and access to justice.',
    },
    {
      id: 'q9',
      question: 'Good citizenship in the context of HRS-201 primarily emphasizes:',
      options: [
        'Political party membership',
        'Tolerance, diversity, and social harmony',
        'Economic productivity',
        'Military service',
      ],
      correct: 1,
      explanation: 'HRS-201 promotes good citizenship through values of tolerance, diversity, cross-cultural understanding, and social harmony.',
    },
    {
      id: 'q10',
      question: 'Which organization\'s charter forms a key study document in HRS-201?',
      options: ['The World Trade Organization', 'The United Nations', 'NATO', 'The World Bank'],
      correct: 1,
      explanation: 'The United Nations Human Rights Charter (UDHR) is one of the two primary documents studied in HRS-201.',
    },
  ],
  'inct-201': [
    {
      id: 'q1',
      question: 'CBIS stands for:',
      options: [
        'Computer Based Internet System',
        'Computer Based Information System',
        'Central Binary Information Storage',
        'Circuit Based Input System',
      ],
      correct: 1,
      explanation: 'CBIS stands for Computer Based Information System — a system that uses computers to process and manage information.',
    },
    {
      id: 'q2',
      question: 'Which of the following is a type of network topology?',
      options: ['RAID', 'Cache', 'Bus', 'Modem'],
      correct: 2,
      explanation: 'Bus is a network topology. Other common topologies include Star and Ring, all covered in INCT-201.',
    },
    {
      id: 'q3',
      question: 'RAM stands for:',
      options: ['Read Access Memory', 'Random Access Memory', 'Rapid Application Module', 'Remote Access Management'],
      correct: 1,
      explanation: 'RAM stands for Random Access Memory — the primary volatile memory used by computers for active processes.',
    },
    {
      id: 'q4',
      question: 'ARPA Net is considered the precursor to:',
      options: ['Bluetooth', 'The Internet', 'Wi-Fi', 'USB technology'],
      correct: 1,
      explanation: 'ARPA Net (Advanced Research Projects Agency Network) was the first wide-area packet-switched network and the precursor to the modern Internet.',
    },
    {
      id: 'q5',
      question: 'Full Duplex transmission allows:',
      options: [
        'Data to flow in one direction only',
        'Data to flow in both directions but not simultaneously',
        'Data to flow in both directions simultaneously',
        'No data flow between devices',
      ],
      correct: 2,
      explanation: 'Full Duplex allows simultaneous two-way communication, unlike Half Duplex (two-way but not simultaneous) or Simplex (one-way only).',
    },
    {
      id: 'q6',
      question: 'Which type of computer is the most powerful and used for large-scale computing tasks?',
      options: ['Mini Computer', 'Micro Computer', 'Mainframe Computer', 'Super Computer'],
      correct: 3,
      explanation: 'Super Computers are the most powerful and are used for complex scientific calculations, weather forecasting, etc.',
    },
    {
      id: 'q7',
      question: 'RAID stands for:',
      options: [
        'Random Array of Independent Disks',
        'Redundant Array of Independent Disks',
        'Rapid Array of Integrated Data',
        'Remote Access to Integrated Drives',
      ],
      correct: 1,
      explanation: 'RAID stands for Redundant Array of Independent Disks — a data storage technology combining multiple disks for redundancy and performance.',
    },
    {
      id: 'q8',
      question: 'LAN stands for:',
      options: ['Large Area Network', 'Local Area Network', 'Linked Access Node', 'Layered Application Network'],
      correct: 1,
      explanation: 'LAN stands for Local Area Network — a network connecting devices within a limited area like a building.',
    },
    {
      id: 'q9',
      question: 'Which of the following is an Input Device?',
      options: ['Monitor', 'Printer', 'Keyboard', 'Speaker'],
      correct: 2,
      explanation: 'A keyboard is an input device used to enter data into a computer. Monitors, printers, and speakers are output devices.',
    },
    {
      id: 'q10',
      question: 'Application Software refers to:',
      options: [
        'The operating system of a computer',
        'Programs designed to help users perform specific tasks',
        'Hardware drivers and firmware',
        'The BIOS of a computer',
      ],
      correct: 1,
      explanation: 'Application software is designed for end users to perform specific tasks like word processing, browsing, etc.',
    },
  ],
  'esci-201': [
    {
      id: 'q1',
      question: 'The Montreal Protocol (1987) was established to address:',
      options: ['Global warming', 'Ozone layer depletion', 'Ocean pollution', 'Deforestation'],
      correct: 1,
      explanation: 'The Montreal Protocol is an international treaty designed to protect the ozone layer by phasing out ozone-depleting substances.',
    },
    {
      id: 'q2',
      question: 'The Kyoto Protocol primarily deals with:',
      options: [
        'Water pollution standards',
        'Biodiversity conservation',
        'Reducing greenhouse gas emissions',
        'Marine protected areas',
      ],
      correct: 2,
      explanation: 'The Kyoto Protocol (1997) commits industrialized countries to reduce greenhouse gas emissions to combat global warming.',
    },
    {
      id: 'q3',
      question: 'Which layer of the atmosphere contains the ozone layer?',
      options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'],
      correct: 1,
      explanation: 'The ozone layer is located in the stratosphere, approximately 15–35 km above Earth\'s surface.',
    },
    {
      id: 'q4',
      question: 'Acid rain is primarily caused by:',
      options: [
        'Carbon dioxide and methane',
        'Sulfur dioxide and nitrogen oxides',
        'Ozone and chlorofluorocarbons',
        'Particulate matter and dust',
      ],
      correct: 1,
      explanation: 'Acid rain forms when sulfur dioxide (SOx) and nitrogen oxides (NOx) react with water vapor to form sulfuric and nitric acids.',
    },
    {
      id: 'q5',
      question: 'GIS stands for:',
      options: [
        'General Information System',
        'Geographic Information System',
        'Global Internet Service',
        'Geological Imaging Software',
      ],
      correct: 1,
      explanation: 'GIS (Geographic Information System) is used in Environmental Science for mapping, analyzing, and managing spatial data.',
    },
    {
      id: 'q6',
      question: 'The Biosphere refers to:',
      options: [
        'The rocky outer layer of the Earth',
        'All water on, above, and below Earth\'s surface',
        'The zone of life encompassing all living organisms',
        'The gaseous envelope surrounding the Earth',
      ],
      correct: 2,
      explanation: 'The Biosphere encompasses all living organisms on Earth and the environments they inhabit.',
    },
    {
      id: 'q7',
      question: 'Which of the following is a greenhouse gas?',
      options: ['Nitrogen (N2)', 'Oxygen (O2)', 'Carbon Dioxide (CO2)', 'Argon (Ar)'],
      correct: 2,
      explanation: 'Carbon dioxide (CO2) is a major greenhouse gas responsible for trapping heat in the atmosphere and contributing to global warming.',
    },
    {
      id: 'q8',
      question: 'Plate Tectonics is studied under which sphere in ESCI-201?',
      options: ['Atmosphere', 'Hydrosphere', 'Biosphere', 'Lithosphere'],
      correct: 3,
      explanation: 'Plate Tectonics, minerals, and rocks are studied under the Lithosphere in the Environmental Science course.',
    },
    {
      id: 'q9',
      question: 'Thermal pollution of water bodies is primarily caused by:',
      options: [
        'Addition of heavy metals',
        'Discharge of heated water from industrial processes',
        'Dumping of plastic waste',
        'Agricultural runoff',
      ],
      correct: 1,
      explanation: 'Thermal pollution occurs when industries discharge heated water into natural water bodies, reducing oxygen levels and harming aquatic life.',
    },
    {
      id: 'q10',
      question: 'Sustainability in Environmental Science means:',
      options: [
        'Using all available natural resources as quickly as possible',
        'Meeting present needs without compromising the ability of future generations to meet their needs',
        'Maximizing economic growth at all costs',
        'Eliminating all industrial activity',
      ],
      correct: 1,
      explanation: 'Sustainability (Brundtland definition) means meeting the needs of the present without compromising the ability of future generations to meet their own needs.',
    },
  ],
}
